[2024-11-22T18:51:30.265+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-22T18:51:30.348+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection.process_transaction scheduled__2024-11-22T18:49:00+00:00 [queued]>
[2024-11-22T18:51:30.406+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection.process_transaction scheduled__2024-11-22T18:49:00+00:00 [queued]>
[2024-11-22T18:51:30.407+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-22T18:51:30.472+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): process_transaction> on 2024-11-22 18:49:00+00:00
[2024-11-22T18:51:30.500+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=555) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-22T18:51:30.505+0000] {standard_task_runner.py:72} INFO - Started process 557 to run task
[2024-11-22T18:51:30.509+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection', 'process_transaction', 'scheduled__2024-11-22T18:49:00+00:00', '--job-id', '413', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_dag.py', '--cfg-path', '/tmp/tmpsudk73qj']
[2024-11-22T18:51:30.516+0000] {standard_task_runner.py:105} INFO - Job 413: Subtask process_transaction
[2024-11-22T18:51:30.652+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection.process_transaction scheduled__2024-11-22T18:49:00+00:00 [running]> on host c6af8dbaf1e5
[2024-11-22T18:51:30.964+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_detection' AIRFLOW_CTX_TASK_ID='process_transaction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-22T18:49:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-22T18:49:00+00:00'
[2024-11-22T18:51:30.967+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-22T18:51:31.016+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-22T18:51:31.053+0000] {fraud_detection_dag.py:77} INFO - Données récupérées depuis XCom: {"columns":["cc_num","merchant","category","amt","first","last","gender","street","city","state","zip","lat","long","city_pop","job","dob","trans_num","merch_lat","merch_long","is_fraud","current_time"],"index":[174034],"data":[[3573030041201292,"fraud_Schuppe LLC","entertainment",27.81,"Joanne","Williams","F","3638 Marsh Union","Altonah","UT",84002,40.3207,-110.436,302,"Sales professional, IT","1990-01-17","096b7ab8209940c08db586b8a864d4b1",39.406429,-109.791519,0,1732301482533]]}
[2024-11-22T18:51:31.054+0000] {fraud_detection_dag.py:85} INFO - Données JSON parsées avec succès
[2024-11-22T18:51:31.062+0000] {fraud_detection_dag.py:89} INFO - DataFrame créé avec 1 lignes
[2024-11-22T18:51:31.066+0000] {fraud_detection_dag.py:93} INFO - Colonnes renommées avec succès
[2024-11-22T18:51:31.067+0000] {fraud_detection_dag.py:94} INFO - Colonnes disponibles: ['cc_num', 'merchant', 'category', 'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip', 'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'merch_lat', 'merch_long', 'is_fraud', 'trans_date_trans_time']
[2024-11-22T18:51:31.074+0000] {fraud_detection_dag.py:98} INFO - Conversion de trans_date_trans_time en unix_time réussie
[2024-11-22T18:51:31.159+0000] {fraud_detection_dag.py:107} INFO - Transformation des données...
[2024-11-22T18:51:34.096+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:172: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

[2024-11-22T18:51:34.501+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/sklearn/ensemble/_base.py:172: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = min(effective_n_jobs(n_jobs), n_estimators)

[2024-11-22T18:51:34.517+0000] {fraud_detection_dag.py:119} INFO - Prediction de fraude: NORMAL, Probabilité: 33.61%
[2024-11-22T18:51:34.846+0000] {fraud_detection_dag.py:125} INFO - Prédiction: NORMAL (Probabilité: 33.61%)
[2024-11-22T18:51:34.848+0000] {python.py:240} INFO - Done. Returned value was: notify_normal
[2024-11-22T18:51:34.850+0000] {branch.py:38} INFO - Branch into notify_normal
[2024-11-22T18:51:34.850+0000] {skipmixin.py:230} INFO - Following branch ('notify_normal',)
[2024-11-22T18:51:34.920+0000] {skipmixin.py:278} INFO - Skipping tasks [('skip_processing', -1), ('notify_fraud', -1)]
[2024-11-22T18:51:35.160+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-22T18:51:35.171+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_detection, task_id=process_transaction, run_id=scheduled__2024-11-22T18:49:00+00:00, execution_date=20241122T184900, start_date=20241122T185130, end_date=20241122T185135
[2024-11-22T18:51:35.283+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-22T18:51:35.460+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-22T18:51:35.486+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2024-11-22T18:51:35.514+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
