[2024-11-02T22:53:20.513+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T22:53:20.551+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_monitoring.test_s3_connection manual__2024-11-02T22:53:15.716728+00:00 [queued]>
[2024-11-02T22:53:20.592+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_monitoring.test_s3_connection manual__2024-11-02T22:53:15.716728+00:00 [queued]>
[2024-11-02T22:53:20.599+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-02T22:53:20.632+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): test_s3_connection> on 2024-11-02 22:53:15.716728+00:00
[2024-11-02T22:53:20.650+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=334) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T22:53:20.657+0000] {standard_task_runner.py:72} INFO - Started process 336 to run task
[2024-11-02T22:53:20.660+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_monitoring', 'test_s3_connection', 'manual__2024-11-02T22:53:15.716728+00:00', '--job-id', '28', '--raw', '--subdir', 'DAGS_FOLDER/monitoring_dag.py', '--cfg-path', '/tmp/tmp8drxrqbo']
[2024-11-02T22:53:20.668+0000] {standard_task_runner.py:105} INFO - Job 28: Subtask test_s3_connection
[2024-11-02T22:53:21.198+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_monitoring.test_s3_connection manual__2024-11-02T22:53:15.716728+00:00 [running]> on host 713744f3b6c0
[2024-11-02T22:53:21.437+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_monitoring' AIRFLOW_CTX_TASK_ID='test_s3_connection' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T22:53:15.716728+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T22:53:15.716728+00:00'
[2024-11-02T22:53:21.439+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T22:53:24.284+0000] {monitoring_dag.py:77} INFO - Buckets disponibles:
[2024-11-02T22:53:24.288+0000] {monitoring_dag.py:79} INFO - - final-project-jedha-team-anne
[2024-11-02T22:53:24.292+0000] {monitoring_dag.py:79} INFO - - fraud-detection-bucket-jedha
[2024-11-02T22:53:24.293+0000] {monitoring_dag.py:82} INFO - 
Test du bucket cible: fraud-detection-bucket-jedha
[2024-11-02T22:53:29.660+0000] {monitoring_dag.py:86} INFO - Test du préfixe: fraud-detection-bucket-jedha
[2024-11-02T22:53:30.215+0000] {monitoring_dag.py:98} INFO - Préfixe vide ou inexistant
[2024-11-02T22:53:30.223+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-02T22:53:30.244+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T22:53:30.246+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_monitoring, task_id=test_s3_connection, run_id=manual__2024-11-02T22:53:15.716728+00:00, execution_date=20241102T225315, start_date=20241102T225320, end_date=20241102T225330
[2024-11-02T22:53:30.334+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T22:53:30.410+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T22:53:30.418+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
