[2024-11-02T23:48:14.482+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T23:48:14.542+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection.process_transaction scheduled__2024-11-02T23:46:00+00:00 [queued]>
[2024-11-02T23:48:14.564+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection.process_transaction scheduled__2024-11-02T23:46:00+00:00 [queued]>
[2024-11-02T23:48:14.566+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-11-02T23:48:14.599+0000] {taskinstance.py:2888} INFO - Executing <Task(BranchPythonOperator): process_transaction> on 2024-11-02 23:46:00+00:00
[2024-11-02T23:48:14.634+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1359) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T23:48:14.646+0000] {standard_task_runner.py:72} INFO - Started process 1361 to run task
[2024-11-02T23:48:14.659+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fraud_detection', 'process_transaction', 'scheduled__2024-11-02T23:46:00+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_dag.py', '--cfg-path', '/tmp/tmpfmj3nf5v']
[2024-11-02T23:48:14.669+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask process_transaction
[2024-11-02T23:48:14.809+0000] {task_command.py:467} INFO - Running <TaskInstance: fraud_detection.process_transaction scheduled__2024-11-02T23:46:00+00:00 [running]> on host 713744f3b6c0
[2024-11-02T23:48:15.040+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='fraud_team' AIRFLOW_CTX_DAG_ID='fraud_detection' AIRFLOW_CTX_TASK_ID='process_transaction' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T23:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-02T23:46:00+00:00'
[2024-11-02T23:48:15.043+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T23:48:15.066+0000] {baseoperator.py:405} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-11-02T23:48:16.438+0000] {fraud_detection_dag.py:115} ERROR - Erreur lors du traitement: columns are missing: {'unix_time'}
[2024-11-02T23:48:16.444+0000] {python.py:240} INFO - Done. Returned value was: skip_processing
[2024-11-02T23:48:16.449+0000] {branch.py:38} INFO - Branch into skip_processing
[2024-11-02T23:48:16.451+0000] {skipmixin.py:230} INFO - Following branch ('skip_processing',)
[2024-11-02T23:48:16.485+0000] {skipmixin.py:278} INFO - Skipping tasks [('notify_normal', -1), ('notify_fraud', -1)]
[2024-11-02T23:48:16.566+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T23:48:16.567+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fraud_detection, task_id=process_transaction, run_id=scheduled__2024-11-02T23:46:00+00:00, execution_date=20241102T234600, start_date=20241102T234814, end_date=20241102T234816
[2024-11-02T23:48:16.654+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T23:48:16.746+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T23:48:16.756+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
